name: assign-me
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          
      - name: Install dependencies
        run: npm install fs @actions/core @actions/github
        
      - name: Assign PR
        env:
          USER_FILE: ${{ secrets.USER_FILE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const core = require('@actions/core');
          const github = require('@actions/github');
          const fs = require('fs');
          
          const users = fs.readFileSync(process.env.USER_FILE, 'utf8');
          const { pull_request } = github.context.payload;
          const user = users.users[Math.abs(pull_request.number) % users.users.length];
        
          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
          const { owner, repo } = github.context.repo;
          const issue_number = pull_request.number;
          
          octokit.issues.addAssignees({
            owner: owner,
            repo: repo,
            issue_number: issue_number,
            assignees: [user.username]
          });
