name: Auto-dislabelling and closing issues on pull requests
on:
  pull_request:
    types: [closed]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LABEL_TO_USE: "In review"
jobs:
  dislabel-close-issue:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Dislabel and close issues
        id: pr_closed_dislabelling
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          body_text="$(echo "${{ github.event.pull_request.body }}" | tr -d '\r\n')"
          url_prs="$(echo "$body_text" | grep -oP 'https://(api\.)?github\.com/[^\s]+\b(?:\([^)]*\))?')"
          for urls_prs in ${url_prs[@]}; do
            urls=$(echo "$urls_prs" | sed 's|https://github.com/|https://api.github.com/repos/|')
            states=$(curl -s -X GET -H "Authorization: Bearer $GITHUB_TOKEN" "$urls" | jq -r '.state')
            if [ "$states" = "closed" ]; then
              message="Issue present in [$PR_NUMBER]($PR_URL)"
              curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"body\": \"$message\"}" "$urls/comments"
            elif [ "$states" = "open" ]; then
              labels=$(curl -s -X GET -H "Authorization: Bearer $GITHUB_TOKEN" "$urls" | jq -r '.labels[].name')
              if grep -q "$LABEL_TO_USE" <<< "$labels"; then
                message="Issue closed by [$PR_NUMBER]($PR_URL)"
                curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"body\": \"$message\"}" "$urls/comments"
                curl -s -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" "${urls}/labels/${LABEL_TO_USE}"
                curl -s -X PATCH -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"state\": \"closed\"}" "$urls"
              fi
            fi
          done
          issue_numbers=$(echo "$body_text" | grep -oP '(?<!\[)#(\d+)(?!\])' | sed 's/#//')
          for issue_number in ${issue_numbers[@]}; do
            url="https://api.github.com/repos/${{ github.repository }}/issues/$issue_number"
            state=$(curl -s -X GET -H "Authorization: Bearer $GITHUB_TOKEN" "$url" | jq -r '.state')
            if [ "$state" = "closed" ]; then
              message="Issue present in [$PR_NUMBER]($PR_URL)"
              curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"body\": \"$message\"}" "$url/comments"
            elif [ "$state" = "open" ]; then
              labels=$(curl -s -X GET -H "Authorization: Bearer $GITHUB_TOKEN" "$url" | jq -r '.labels[].name')
              if grep -q "$LABEL_TO_USE" <<< "$labels"; then
                message="Issue closed by [$PR_NUMBER]($PR_URL)"
                curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"body\": \"$message\"}" "$url/comments"
                curl -s -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" "${url}/labels/${LABEL_TO_USE}"
                curl -s -X PATCH -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"state\": \"closed\"}" "$url"
              fi
            fi
          done
