name: Auto-dislabelling and closing issues on pull requests
on:
  pull_request:
    types: [closed]
env:
  HEADER: Authorization:Bearer ${{ secrets.GITHUB_TOKEN }}
  LABEL_TO_USE: "In review"
jobs:
  dislabel-close-issue:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Dislabel and close issues
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          body_text="$(echo "${{ github.event.pull_request.body }}" | tr -d '\r\n')"
          message="Issue closed by PR [#$PR_NUMBER]($PR_URL)"
          url_prs=$(echo "$body_text" | grep -oP 'https://(api\.)?github\.com/[^\s]+\b(?:\([^)]*\))?')
          issue_numbers=$(echo "$body_text" | grep -oP '(?<!\[)#(\d+)(?!\])' | sed 's/#//')
          combined=$(paste <(echo "$url_prs") <(echo "$issue_numbers"))
          for combined_url in ${combined[@]}; do
            if [[ "$combined_url" =~ ^http ]]; then
              url=$(echo "$combined_url" | sed 's|https://github.com/|https://api.github.com/repos/|')
            else
              issue_number="$combined_url"
              url="https://api.github.com/repos/${{ github.repository }}/issues/$issue_number"
            fi
            state=$(curl -s -X GET -H "$HEADER" "$url" | jq -r '.state')
            curl -s -X POST -H "$HEADER" -d "{\"body\": \"$message\"}" "$url/comments"
            if [ "$state" = "open" ]; then
              label_url=$(echo "${url}/labels/$LABEL_TO_USE" | sed 's/ /%20/g')
              labels=$(curl -s -X GET -H "$HEADER" "$url" | jq -r '.labels[].name')
              curl -s -X POST -H "$HEADER" -d "{\"body\": \"$message\"}" "$url/comments"
              curl -s -X PATCH -H "$HEADER" -d "{\"state\": \"closed\"}" "$url"
              if grep -q "$LABEL_TO_USE" <<< "$labels"; then
                curl -s -X DELETE -H "$HEADER" "$label_url"
              fi
            fi
          done
