name: get pull request details
on:
  pull_request:
    types: [closed, sinchronize]
 #   branches: [main]
jobs:
  merge-comment:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get pull request details
  id: pr-details
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}"
    response=$(curl -X GET -H "Authorization: Bearer $GITHUB_TOKEN" -H "Content-Type: application/json" -H "X-GitHub-Api-Version: 2022-11-28" $URL)
    echo "::set-output name=author::$(echo $response | jq -r '.user.login')"

- name: Create Comment
  env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      BODY_TEXT: "I have merged into main 2\n\nOpened by: ${{ steps.pr-details.outputs.author }}"
  run: |
    URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
    curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -H "X-GitHub-Api-Version: 2022-11-28" $URL -d "{\"body\": \"$BODY_TEXT\"}"
