name: Auto-labelling of issues on pull requests
on:
  pull_request:
    types: [opened, synchronize]
env:
  HEADER: Authorization:Bearer ${{ secrets.GITHUB_TOKEN }}
  LABEL_TO_USE: "In review"
jobs:
  labelling-issue:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Labelling issues
        id: pr_open_labelling
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          body_text="$(echo "${{ github.event.pull_request.body }}" | tr -d '\r\n')"
          url_prs=$(echo "$body_text" | grep -oP 'https://(api\.)?github\.com/[^\s]+\b(?:\([^)]*\))?')
          issue_numbers=$(echo "$body_text" | grep -oP '(?<!\[)#(\d+)(?!\])' | sed 's/#//')
          combined=$(paste <(echo "$url_prs") <(echo "$issue_numbers"))
          for combined_url in ${combined[@]}; do
            if [[ "$combined_url" =~ ^http ]]; then
              url=$(echo "$combined_url" | sed 's|https://github.com/|https://api.github.com/repos/|')
              type="url"
            else
              issue_number="$combined_url"
              url="https://api.github.com/repos/${{ github.repository }}/issues/$issue_number"
              type="issue"
            fi
            state=$(curl -s -X GET -H "$HEADER" "$url" | jq -r '.state')
            if [ "$state" = "open" ] && [ "$type" = "url" ] || [ "$type" = "issue" ]; then
                labels=$(curl -s -X GET -H "$HEADER" "$url" | jq -r '.labels[].name')
                if ! grep -q "$LABEL_TO_USE" <<< "$labels"; then
                curl -s -X POST -H "$HEADER" -d "{\"labels\": [\"$LABEL_TO_USE\"]}" "$url/labels"
                fi
            fi
          done
