name: test rub ok

on:
  pull_request:
    types: [closed, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  merge-comment:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract URL from PR body
        id: extract-url
        run: |
          body_text="$(echo "${{ github.event.pull_request.body }}" | tr -d '\r\n')"
          echo "$body_text"
          urls="$(echo "$body_text" | grep -oP 'https?://[^\s]+\b(?:\([^)]*\))?')"
          echo "$urls"
          issue_numbers=$(echo "$body_text" | grep -oP '(?<!\[)#(\d+)(?!\])')
          if [ -z "$issue_numbers" ]; then
            echo "No issue numbers found."
           else
            echo "$issue_numbers"
          fi
      - name: add-comment
        run: |
          url_comments=$(echo "$urls" | sed 's/github\.com\/\([^\/]*\)\/\([^\/]*\)\/issues\/\([0-9]*\)/api.github.com\/repos\/\1\/\2\/issues\/\3\/comments/')
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d '{"body": "This is my comment"}' "$url_comments"
