name: test rub ok

on:
  pull_request:
    types: [closed, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  merge-comment:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract URL from PR body
        id: extract-url
        run: |
          body_text="$(echo "${{ github.event.pull_request.body }}" | tr -d '\r\n')"
          echo "$body_text"
          urls="$(echo "$body_text" | grep -oP 'https?://[^\s]+\b(?:\([^)]*\))?')"
          echo "$urls"
          issue_numbers=$(echo "$body_text" | grep -oP '(?<!\[)#(\d+)(?!\])')
          if [ -z "$issue_numbers" ]; then
            echo "No issue numbers found."
           else
            echo "$issue_numbers"
          fi
      - name: Generate URL for comments
        env:
          TEXT: Branch ${{ github.event.pull_request.head.ref }} merged over ${{ github.event.pull_request.base.ref }} by user ${{ github.event.pull_request.user.login }} and merged by ${{ github.event.pull_request.merged_by.login }}
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/issues/$issue_numbers/comments"
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -H "X-GitHub-Api-Version: 2022-11-28" $URL -d "{\"body\": \"$TEXT\"}"
